### ISSUE TITLE
Add EdgeXFoundry to Connectivity

### ISSUE THREAD

**Issue by yanghua** [State-of-the-Edge/landscape#10]
EdgeX Foundry is a vendor-neutral open source project hosted by The Linux Foundation building a common open framework for IoT edge computing.  At the heart of the project is an interoperability framework hosted within a full hardware- and OS-agnostic reference software platform to enable an ecosystem of plug-and-play components that unifies the marketplace and accelerates the deployment of IoT solutions.

EdgeX is an important enabler for interested parties to freely collaborate on open and interoperable IoT solutions built using existing connectivity standards combined with their own proprietary innovations.

EdgeX Foundry goals include:

- Build and promote EdgeX as the common open platform unifying Internet of Things (IoT) edge computing
- Enable and encourage the rapidly growing community of IoT solutions providers to create an ecosystem of interoperable plug-and-play components around the EdgeX platform architecture
- Certify EdgeX components to ensure interoperability and compatibility
- Provide tools to quickly create EdgeX-based IoT edge solutions that can easily adapt to changing business needs
- Collaborate with relevant open source projects, standards groups, and industry alliances to ensure consistency and interoperability across the IoT

Official web site : https://www.edgexfoundry.org/
Asset Library url : https://www.edgexfoundry.org/news/asset-library/
Project Logo url : https://www.edgexfoundry.org/wp-content/uploads/sites/25/2017/04/logo_edgex_foundry_4x.png

**Comment by KimiMa** [comment]
#6 is the same request.

**Comment by yanghua** [comment]
@KimiMa OK, Thanks for reminding me, closing this issue.
