### ISSUE TITLE
Weak Criteria

### ISSUE THREAD

**Issue by dtoubelis** [State-of-the-Edge/landscape#11]
I wonder what your qualification criteria is. In my opinion 90% of companies listed here have nothing to do with edge computing. It is no secret that every business will try to benefit from any new hype and will do anything to put their name in the context. But when somebody endorses those businesses I would highly question credibility of their reports and rather treat them rather as paid marketing than anything meaningful. 

In my opinion there are only 3 category to edge computing:
- manufacturing of gateway devices - there is nothing interesting going here, we are just waiting for manufacturers to get it right, i.e. to come up with devices with proper set of features.
- connectivity - also not much excitement. I would expect standardization of 4G, LTE, 5G interfaces and sensible plans from wireless network operators, and maybe some standardization on mesh networking.
- but holy grail of Edge Computing is software that runs on edge devices and uses swarm intelligence, smart clustering, distributed storage and networking and is capable of running on relatively small gateway devices and scale horizontally virtually infinitely using smart algorithms.

So, out of your list some 10% of mentioned companies have anything to do with the above 3 categories.

BTW, I would consider cloud to be irrelevant for edge computing. It has some uses now but it is on its way to be obsoleted by fog computing.

**Comment by mtrifiro** [comment]
We define edge computing to include the infrastructure edge in addition to the device edge. I have personal knowledge of legitimate edge computing efforts for the majority of the companies and groups mentioned.

That said, we would welcome additions from you areas of expertise.
